/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FormInicio.java
 *
 * Created on 02/03/2011, 05:14:32
 */

package Forms;

import Entidades.Proyecto;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 *
 * @author Manuel Lorenze
 */
public class FormInicio extends javax.swing.JFrame {

    /** Creates new form FormInicio */
    public FormInicio(String paisIdioma, String lenguajeIdioma) {
        lugarConfigurado = new Locale(paisIdioma, lenguajeIdioma);
        initComponents();
        setearEtiquetas();
        obtenerProyectosAlmacenados();
    }

    private Locale lugarConfigurado;
    private List<Proyecto> proyectos;

    /**
     * Se setean las etiquetas de la pantalla.
     */
    private void setearEtiquetas(){
        setTitle("Módulo PERT"); // Manejo de idioma!!!
        lblListaDeProyectos.setText("Lista de proyectos almacenados:"); // Manejo de idioma!!!
        btnNuevo.setText("Nuevo"); // Manejo de idioma!!!
        btnAbrir.setText("Abrir"); // Manejo de idioma!!!
        btnBorrar.setText("Borrar"); // Manejo de idioma!!!
        btnSalir.setText("Salir"); // Manejo de idioma!!!
    }

    /**
     * Se obtienen los proyectos que previamente han sido ingresados al sistema y almacenados en los archivos de persistencia.
     */
    private void obtenerProyectosAlmacenados(){
        proyectos = new ArrayList<Proyecto>();

        // Lógica de acceso a los archivos con proyectos almacenados!!!

        for(int i = 0; i < proyectos.size(); i++){
            cmbListaDeProyectos.addItem(proyectos.get(i).obtenerNombre());
        }
        cmbListaDeProyectos.updateUI();       
    }

    /**
     * Se agrega un proyecto creado recientemente a la lista de proyectos existente.
     * @param p
     */
    public void agregarProyectoEnListaDeProyectos(Proyecto p){
        proyectos.add(p);
        cmbListaDeProyectos.addItem(p.obtenerNombre());
        cmbListaDeProyectos.updateUI();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNuevo = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        lblListaDeProyectos = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();
        cmbListaDeProyectos = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNuevo.setText("btnNuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnAbrir.setText("btnAbrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnBorrar.setText("btnBorrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        lblListaDeProyectos.setText("lblListadoDeProyectos");

        btnSalir.setText("btnSalir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnNuevo, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(btnAbrir, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(btnBorrar, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblListaDeProyectos)
                            .addComponent(cmbListaDeProyectos, javax.swing.GroupLayout.Alignment.TRAILING, 0, 260, Short.MAX_VALUE)))
                    .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblListaDeProyectos)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbListaDeProyectos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbrir)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBorrar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 101, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        FormProyecto fp = new FormProyecto(this);
        fp.setVisible(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        Proyecto proyecto = proyectos.get(cmbListaDeProyectos.getSelectedIndex());
        FormProyecto fp = new FormProyecto(this, proyecto);
        fp.setVisible(true);
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        int i = cmbListaDeProyectos.getSelectedIndex();        
        cmbListaDeProyectos.removeItemAt(i);
        proyectos.remove(i);
        cmbListaDeProyectos.updateUI();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    // Este main se deja sin efecto dado que el inicio del programa se maneja desde la clase pert/Main.java
    /**
    * @param args the command line arguments
    */
    /*public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormInicio().setVisible(true);
            }
        });
    }*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox cmbListaDeProyectos;
    private javax.swing.JLabel lblListaDeProyectos;
    // End of variables declaration//GEN-END:variables

}
